Update lamp_deploy.yaml. go

diff --git a/.github/workflows/lamp_deploy.yaml b/.github/workflows/lamp_deploy.yaml
--- a/.github/workflows/lamp_deploy.yaml
+++ b/.github/workflows/lamp_deploy.yaml
@@ -35,6 +35,22 @@ jobs:
             sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
             sudo docker run hello-world
 
+      - name: Find and Change Directory to docker-compose.yml
+        uses: appleboy/ssh-action@v1.0.0
+        with:
+          host: ${{ secrets.STAGING_SERVER_IP }}
+          username: ubuntu
+          key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            path=$(find / -name "docker-compose.yml" 2>/dev/null)
+            if [ -n "$path" ]; then
+              cd "$(dirname "$path")" || exit 1
+            else
+              echo "docker-compose.yml not found"
+              exit 1
+            fi
+
       - name: Run Docker Compose
         uses: appleboy/ssh-action@v1.0.0
         with:
