2nd commit

diff --git a/.github/workflows/lamp_deploy.yaml b/.github/workflows/lamp_deploy.yaml
--- a/.github/workflows/lamp_deploy.yaml
+++ b/.github/workflows/lamp_deploy.yaml
@@ -10,24 +10,49 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: SSH into Staging Server and Install Docker
-        uses: appleboy/ssh-action@v1.0.0
-        with:
-          host: ${{ secrets.STAGING_SERVER_IP }}
-          username: ubuntu
-          key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
-          port: 22
-          script: |
-            sudo apt-get update
-            sudo apt-get install -y docker.io
 
-           
-            mkdir app && cd app || exit
+    - name: Installing Docker on Assignment/Test Server
+      uses: appleboy/ssh-action@v1.0.0
+      with:
+        host: ${{ secrets.ASSIGNMENT_SERVER_IP }}
+        username: ubuntu
+        key: ${{ secrets.ASSIGNMENT_SERVER_SSH_PRIVATE_KEY }}
+        port: 22
+        script: |
+          sudo apt-get update
+          sudo apt-get install -y ca-certificates curl gnupg 
+          sudo install -m 0755 -d /etc/apt/keyrings
+          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
+          sudo chmod a+r /etc/apt/keyrings/docker.gpg
+          echo \
+          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+          sudo apt-get update
+          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+          sudo docker run hello-world
 
-           
-            cp Dockerfile .
-            cp docker-compose.yml .
-
-           
-            sudo docker-compose up -d
-
+    - name: Find and Change Directory to docker-compose.yml
+      uses: appleboy/ssh-action@v1.0.0
+      with:
+        host: ${{ secrets.STAGING_SERVER_IP }}
+        username: ubuntu
+        key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
+        port: 22
+        script: |
+          path=$(find / -name "docker-compose.yaml" 2>/dev/null)
+          if [ -n "$path" ]; then
+            cd "$(dirname "$path")" || exit 1
+          else
+            echo "docker-compose.yaml not found"
+            exit 1
+          fi
+    - name: Run Docker Compose
+      uses: appleboy/ssh-action@v1.0.0
+      with:
+        host: ${{ secrets.STAGING_SERVER_IP }}
+        username: ubuntu
+        key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
+        port: 22
+        script: |
+          sudo docker-compose up -d
